version: '3'

services:
  explorer:
    image: alethio/ethereum-lite-explorer
    environment:
      - APP_NODE_URL=http://localhost:8545
    ports:
      - 8080:80
  ganache:
    build:
      context: ./ganache-cli
    environment:
      - WEB3_FORK_URL=${WEB3_FORK_URL}
    ports:
      - "8545:8545"
