[package]
name = "ethane-abi"
version = "0.1.0"
authors = ["Mark Melczer <melczer7@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.4.3"
ethereum-types = "0.11"
serde_json = "1.0"
sha3 = "0.9.1"
thiserror = "1.0"

[dev-dependencies]
hex-literal = "0.3"
