[package]
name = "test-helper"
version = "0.1.0"
authors = ["thojest <thojest@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
ethane = { path = "../" }
serde = "1"
serde_json = "1"
sha3 = "0.9.1"
rand = "0.8"
regex = "1"
