[package]
name = "ethane-types"
version = "0.1.0"
authors = ["ZGEN <info@zgen.hu>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_test = "1"
