name: Ethane Rust runs against Geth 1.9.25

# you can save compilation hours on Github if you only run this on pull
# requests or when directly pushing to main branch
on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          # profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  test:
    runs-on: ubuntu-latest
    services:
      ganache:
        image: zgen/geth:v0.3.2
        ports:
          - 8545:8545
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Dependencies
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y solc
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

